# Generated by Django 3.2.3 on 2021-05-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210527_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='이름을 입력해주세요', max_length=100),
        ),
    ]
